---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: https
    nginx.ingress.kubernetes.io/secure-backends: 'true'
    nginx.org/ssl-services: openunison-{{ .Release.Name }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: openunison-tekton-{{ .Release.Name }}
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    kubernetes.io/ingress.class: nginx
    {{ range $key,$value := .Values.network.ingress_annotations }}
    {{ $key }}: {{ quote $value }}
    {{ end }}
  name: openunison-tekton-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: tekton-db
    app.kubernetes.io/part-of: openunison
spec:
  rules:
  - host: {{ .Values.openunison.non_secret_data.tektondashboard_host }}
    http:
      paths:
      - backend:
          service:
            name: openunison-orchestra
            port: 
              number: 443
        path: "/"
        pathType: Prefix
  
  tls:
  - hosts:
    - {{ .Values.openunison.non_secret_data.tektondashboard_host }}
    secretName: tektondb-tls-certificate