---
apiVersion: openunison.tremolo.io/v1
kind: Workflow
metadata:
  name: create-operations-dev
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openunison
    app.kubernetes.io/instance: openunison-{{ .Release.Name }}
    app.kubernetes.io/component: openunison-workflows
    app.kubernetes.io/part-of: openunison
spec:
  description: Create dev operations project in gitlab
  inList: false
  label: Create Dev Operations Application
  orgId: 9d251de8-e481-45da-b22c-c8c98952e581
  dynamicConfiguration:
    dynamic: false
    className: ""
    params: []
  tasks: |-
    
    # fork the production git project
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.ForkProject
      params:
        sourceProjectName: $nameSpace$-operations
        sourceProjectNamespace: $nameSpace$-production
        destinationNamespace: $nameSpace$-dev
        targetName: gitlab
        gitSshHost: {{ .Values.openunison.non_secret_data.GITLAB_SSH_HOST | quote }}

    # create a deployment key for argocd to use
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.CreateDeploymentKey
      params:
        targetName: gitlab
        namespace: $nameSpace$-dev
        project: $nameSpace$-operations
        keyLabel: argocd
        makeWriteable: "false"
        privateKeyReuestName: argoPullSecretB64
        privateKeyReuestNamePT: argoPullSecret


    # create a git repo in argocd that is connected to our operations project in gitlab
    - taskType: customTask
      className: com.tremolosecurity.argocd.tasks.CreateGitRepository
      params:
        type: git
        name: $nameSpace$-operations
        repoUrl: "$gitSshInternalURL$"
        sshPrivateKey: $argoPullSecret$
        target: argocd

    # approvers need to be able to approve pull requests
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.AddGroupToProject
      params:
        projectName: $nameSpace$-operations
        namespace: $nameSpace$-dev
        groupName: approvers-k8s-$nameSpace$
        targetName: gitlab
        accessLevel: MAINTAINER

    # operations need to be able to fork for development
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.AddGroupToProject
      params:
        projectName: $nameSpace$-operations
        namespace: $nameSpace$-dev
        groupName: k8s-namespace-operations-$nameSpace$
        targetName: gitlab
        accessLevel: DEVELOPER

    # developers need to be able to fork for development
    - taskType: customTask
      className: com.tremolosecurity.unison.gitlab.provisioning.tasks.AddGroupToProject
      params:
        projectName: $nameSpace$-operations
        namespace: $nameSpace$-dev
        groupName: k8s-namespace-developer-$nameSpace$
        targetName: gitlab
        accessLevel: DEVELOPER

    
    # create the dev namespace
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: Namespace
        url: /api/v1/namespaces
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/namespaces/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev.yaml
        template: |-
          kind: Namespace
          apiVersion: v1
          metadata:
            name: $nameSpace$-dev
            labels:
              name: $nameSpace$-dev
              application: $nameSpace$
              type: application
              env: dev

    # create rolebinding for admins
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: RoleBinding
        url: /apis/rbac.authorization.k8s.io/v1/namespaces/$nameSpace$-dev/rolebindings
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/namespaces/$nameSpace$/$nameSpace$-dev/rolebindings/operations-binding.yaml
        template: |-
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: operations-binding
            namespace: $nameSpace$-dev
          subjects:
            - kind: Group
              name: k8s-namespace-operations-$nameSpace$
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: admin
            apiGroup: rbac.authorization.k8s.io

    # create rolebinding for developers
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: RoleBinding
        url: /apis/rbac.authorization.k8s.io/v1/namespaces/$nameSpace$-dev/rolebindings
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/namespaces/$nameSpace$/$nameSpace$-dev/rolebindings/developers-binding.yaml
        template: |-
          kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: developers-binding
            namespace: $nameSpace$-dev
          subjects:
            - kind: Group
              name: k8s-namespace-developer-$nameSpace$
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: view
            apiGroup: rbac.authorization.k8s.io

    # create gatekeeper policies
    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPAllowPrivilegeEscalationContainer
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spspallowprivilegeescalationcontainer
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-privilege-escalation-deny-all.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPAllowPrivilegeEscalationContainer
          metadata:
            name: $nameSpace$-dev-privilege-escalation-deny-all
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPCapabilities
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spspcapabilities
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-capabilities-drop-all.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPCapabilities
          metadata:
            name: $nameSpace$-dev-capabilities-drop-all
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]
            parameters:
              requiredDropCapabilities: ["all"]
              allowedCapabilities: []

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPForbiddenSysctls
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spspforbiddensysctls
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-forbid-all-sysctls.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPForbiddenSysctls
          metadata:
            name: $nameSpace$-dev-psp-forbid-all-sysctls
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]
            parameters:
              forbiddenSysctls:
              - "*"

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPHostFilesystem
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spsphostfilesystem
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-deny-host-filesystem.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPHostFilesystem
          metadata:
            name: $nameSpace$-dev-psp-deny-host-filesystem
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]
            parameters:
              allowedHostPaths: []

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPHostNamespace
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spsphostnamespace
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-bloack-all-host-namespace.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPHostNamespace
          metadata:
            name: $nameSpace$-dev-psp-bloack-all-host-namespace
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPHostNetworkingPorts
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spsphostnetworkingports
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-deny-all-host-network-ports.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPHostNetworkingPorts
          metadata:
            name: $nameSpace$-dev-psp-deny-all-host-network-ports
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]
            parameters:
              hostNetwork: false

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPPrivilegedContainer
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spspprivilegedcontainer
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-deny-all-privileged-container.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPPrivilegedContainer
          metadata:
            name: $nameSpace$-dev-psp-deny-all-privileged-container
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPProcMount
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spspprocmount
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-proc-mount-default.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPProcMount
          metadata:
            name: $nameSpace$-dev-psp-proc-mount-default
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]
            parameters:
              procMount: Default

    - taskType: customTask
      className: com.tremolosecurity.provisioning.tasks.CreateK8sObject
      params:
        targetName: k8s
        kind: K8sPSPAllowedUsers
        url: /apis/constraints.gatekeeper.sh/v1beta1/k8spspallowedusers
        srcType: yaml
        writeToRequest: "true"
        requestAttribute: state-application-$nameSpace$
        path: /src/cluster/gatekeeper/$nameSpace$/$nameSpace$-dev/$nameSpace$-dev-psp-pods-allowed-user-ranges.yaml
        template: |-
          apiVersion: constraints.gatekeeper.sh/v1beta1
          kind: K8sPSPAllowedUsers
          metadata:
            name: $nameSpace$-dev-psp-pods-allowed-user-ranges
          spec:
            match:
              kinds:
                - apiGroups: [""]
                  kinds: ["Pod"]
              namespaces: ["$nameSpace$-dev"]
            parameters:
              runAsUser:
                rule: MustRunAs # MustRunAsNonRoot # RunAsAny 
                ranges:
                  - min: 100
                    max: 4294967294
              runAsGroup:
                rule: MustRunAs # MayRunAs # RunAsAny 
                ranges:
                  - min: 100
                    max: 4294967294
              supplementalGroups:
                rule: MustRunAs # MayRunAs # RunAsAny 
                ranges:
                  - min: 100
                    max: 4294967294
              fsGroup:
                rule: MustRunAs # MayRunAs # RunAsAny 
                ranges:
                  - min: 100
                    max: 4294967294

