apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-wildcard-tls-internal-ca
  namespace: gitlab
spec:
  secretName: gitlab-wildcard-tls-internal-ca
  dnsNames:
  - apps.IPADDR.nip.io
  - "*.apps.IPADDR.nip.io"
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io